pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r HTML/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master  # o 'main', según el nombre de tu rama
